ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS task_id UUID REFERENCES tasks(id) ON DELETE SET NULL;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS finalize_task BOOLEAN NOT NULL DEFAULT TRUE;
CREATE INDEX IF NOT EXISTS agent_runs_task_idx ON agent_runs(task_id) WHERE task_id IS NOT NULL;
