import{ForbiddenException}from"@nestjs/common";import{CollaborationService}from"./collaboration.service";

describe("CollaborationService",()=>{
 const agents=[{id:"agent-1",employeeId:"employee-1",companyId:"company-1",permissions:["agent.collaborate"]},{id:"agent-2",employeeId:"employee-2",companyId:"company-1",permissions:["agent.collaborate"]}];
 const agentService={receiveDelegatedResult:jest.fn()};
 const make=(org:any,tasks:any,bus:any={publish:jest.fn(),publishResponse:jest.fn()})=>new CollaborationService(bus,{create:jest.fn().mockResolvedValue({id:"message-1"})} as any,{publish:jest.fn()} as any,org,tasks,agentService as any);
 it("rejects self delegation",async()=>{const service=make({agents:jest.fn().mockResolvedValue(agents)},{getForCompany:jest.fn().mockResolvedValue({id:"task-1",companyId:"company-1"})});await expect(service.requestTask({taskId:"task-1",senderAgentId:"agent-1",receiverAgentId:"agent-1",companyId:"company-1",type:"TASK_REQUEST",payload:{}}, "employee-1")).rejects.toBeInstanceOf(ForbiddenException);});
 it("rejects agents outside the company",async()=>{const bus={publish:jest.fn()};const service=make({agents:jest.fn().mockResolvedValue([{...agents[0]},{...agents[1],companyId:"company-2"}])},{getForCompany:jest.fn().mockResolvedValue({id:"task-1",companyId:"company-1"})},bus);await expect(service.requestTask({taskId:"task-1",senderAgentId:"agent-1",receiverAgentId:"agent-2",companyId:"company-1",type:"TASK_REQUEST",payload:{}}, "employee-1")).rejects.toBeInstanceOf(ForbiddenException);expect(bus.publish).not.toHaveBeenCalled();});
 it("rejects a receiver that is not present",async()=>{const service=make({agents:jest.fn().mockResolvedValue([agents[0]])},{getForCompany:jest.fn().mockResolvedValue({id:"task-1",companyId:"company-1"})});await expect(service.requestTask({taskId:"task-1",senderAgentId:"agent-1",receiverAgentId:"agent-2",companyId:"company-1",type:"TASK_REQUEST",payload:{}}, "employee-1")).rejects.toBeInstanceOf(ForbiddenException);});
 it("rejects receiver without collaboration permission",async()=>{const service=make({agents:jest.fn().mockResolvedValue([{...agents[0]},{...agents[1],permissions:[]}])},{getForCompany:jest.fn().mockResolvedValue({id:"task-1",companyId:"company-1"})});await expect(service.requestTask({taskId:"task-1",senderAgentId:"agent-1",receiverAgentId:"agent-2",companyId:"company-1",type:"TASK_REQUEST",payload:{}}, "employee-1")).rejects.toBeInstanceOf(ForbiddenException);});
 it("persists a valid task request",async()=>{const bus={publish:jest.fn().mockResolvedValue("stream-1")};const messages={create:jest.fn().mockResolvedValue({id:"message-1"})};const activity={publish:jest.fn().mockResolvedValue(undefined)};const org={agents:jest.fn().mockResolvedValue(agents)};const tasks={getForCompany:jest.fn().mockResolvedValue({id:"task-1",companyId:"company-1",projectId:"project-1",assignedAgentId:"agent-2"}),updateStatus:jest.fn().mockResolvedValue({})};const service=new CollaborationService(bus as any,messages as any,activity as any,org as any,tasks as any,agentService as any);const result=await service.requestTask({taskId:"task-1",senderAgentId:"agent-1",receiverAgentId:"agent-2",companyId:"company-1",projectId:"project-1",type:"TASK_REQUEST",payload:{title:"Run QA",description:"Execute tests"}},"employee-1");expect(tasks.updateStatus).toHaveBeenCalledWith("task-1","IN_PROGRESS","company-1");expect(messages.create).toHaveBeenCalled();expect(activity.publish).toHaveBeenCalled();expect(bus.publish).toHaveBeenCalled();expect(result).toBe("stream-1");});
 it("rejects project mismatch",async()=>{const service=make({agents:jest.fn().mockResolvedValue(agents)},{getForCompany:jest.fn().mockResolvedValue({id:"task-1",companyId:"company-1",projectId:"project-1",assignedAgentId:"agent-2"})});await expect(service.requestTask({taskId:"task-1",senderAgentId:"agent-1",receiverAgentId:"agent-2",companyId:"company-1",projectId:"project-2",type:"TASK_REQUEST",payload:{}}, "employee-1")).rejects.toBeInstanceOf(ForbiddenException);});
 it("persists a valid response",async()=>{const bus={publish:jest.fn(),publishResponse:jest.fn().mockResolvedValue("response-1")};const messages={create:jest.fn().mockResolvedValue({id:"message-2"})};const activity={publish:jest.fn().mockResolvedValue(undefined)};const org={agents:jest.fn().mockResolvedValue(agents)};const task={id:"task-1",companyId:"company-1",projectId:"project-1",assignedAgentId:"agent-2",status:"IN_PROGRESS"};const tasks={getForCompany:jest.fn().mockResolvedValueOnce(task).mockResolvedValueOnce({...task,status:"COMPLETED"}),updateStatus:jest.fn().mockResolvedValue({...task,status:"COMPLETED"})};const service=new CollaborationService(bus as any,messages as any,activity as any,org as any,tasks as any,agentService as any);const result=await service.respondTask({taskId:"task-1",senderAgentId:"agent-2",receiverAgentId:"agent-1",companyId:"company-1",projectId:"project-1",type:"TASK_RESPONSE",payload:{status:"COMPLETED",response:"QA passed"}},"employee-2");expect(tasks.updateStatus).toHaveBeenCalledWith("task-1","COMPLETED","company-1");expect(bus.publishResponse).toHaveBeenCalled();expect(result.task.status).toBe("COMPLETED");});
 it("rejects response from an unassigned agent",async()=>{const service=make({agents:jest.fn().mockResolvedValue(agents)},{getForCompany:jest.fn().mockResolvedValue({id:"task-1",companyId:"company-1",assignedAgentId:"agent-1",status:"IN_PROGRESS"})});await expect(service.respondTask({taskId:"task-1",senderAgentId:"agent-2",receiverAgentId:"agent-1",companyId:"company-1",type:"TASK_RESPONSE",payload:{}}, "employee-2")).rejects.toBeInstanceOf(ForbiddenException);});
});